### ISSUE TITLE
Latest Version Error.

### ISSUE THREAD

**Issue by BenedictThompson-zz** [md678685/justcord-3#3]
I updated to the latest version but on server start, I get this error:

`JC3MP SERVER/packages/justcord-3-master/util.js:3
        return eval(`\`${template.replace(/`/g, '\\`')}\``);
                                 ^

TypeError: Cannot read property 'replace' of undefined
    at evalTemplate (/home/JamesandJohn/JC3MP SERVER/packages/justcord-3-master/util.js:3:34)
    at formatTopic (/home/JamesandJohn/JC3MP SERVER/packages/justcord-3-master/jcevents.js:31:12)
    at Timeout.setTimeout (/home/JamesandJohn/JC3MP SERVER/packages/justcord-3-master/jcevents.js:62:14)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
`

**Comment by mdcfe** [comment]
You need to keep updating your config when you update Justcord to ensure you include all of the new values. This particular error is caused by not specifying the template for ~~chat~~ the Discord topic updater (`formatting.gameToDiscord.topic` in config.json). 

I'll work on setting default values to the config later on, and hopefully once I've finalised 1.0 the config shouldn't change as frequently.

Let me know how you get on.

**Comment by BenedictThompson-zz** [comment]
Ok!

**Comment by mdcfe** [comment]
Apologies, misread the trace; it's the topic formatting you need to set, not the chat formatting.
